id: P0ABA5AFD
initial_creation_type: ocr
source_metadata:
  volumes:
    b7aeecc2fa5741e7a6e8bd53ac7d6717:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མའི་བསྟན་བཅོས་རིགས་པ་ལ་འཇུག་པ།
      total_pages: 1198
      volume_number: 97
